nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "recma-jsx@*":
    peerDependencies:
      acorn: "*"
  "@mdx-js/mdx@*":
    peerDependencies:
      acorn: "*"
  "@mdx-js/esbuild@*":
    peerDependencies:
      acorn: "*"
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      "search-insights": "*"
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
      algoliasearch:
        optional: true
      "search-insights":
        optional: true
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
      algoliasearch:
        optional: true
  "@algolia/autocomplete-preset-algolia@*":
    peerDependencies:
      "@algolia/client-search": "*"
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
      react:
        optional: true
      "@types/react":
        optional: true
  "kbar@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "react-virtual@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "next-themes@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
